application: palidictionary
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /js/jsonPrefixWords\.js
  static_files: static/jsonPrefixWords.js
  upload: static/jsonPrefixWords\.js

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /admin/.*
  script: admin.app
  login: admin

- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest

